name: Executar Robo de Noticias

on:
  schedule:
    # Roda automaticamente a cada 1 hora
    - cron: '0 * * * *'
  workflow_dispatch: # Permite que você aperte o botão para rodar manualmente

jobs:
  rodar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar ferramentas necessarias
        run: |
          pip install feedparser google-generativeai

      - name: Executar Robo
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python cron_script.py

      - name: Salvar e Enviar as Noticias para o Repositorio
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add banco_noticias.json || true
          git commit -m "Automatizado: Atualizando banco de noticias [skip ci]" || true
          git push || true
